version: '3.7'
services:
    client:
        build:
            context: ./client
            args:
                REACT_APP_REST_API: ${REACT_APP_REST_API:-/api}
        ports:
            - '8000:8000'
        restart: always
    rest:
        build:
            context: ./rest
            args:
                OPEN_LIBRARY_URL: ${OPEN_LIBRARY_URL-http://openlibrary.org}
                OPEN_LIBRARY_COVER_URL: ${OPEN_LIBRARY_COVER_URL-https://covers.openlibrary.org}
        ports:
            - '8080:8080'
        restart: always
    proxy:
        build:
            context: ./proxy
            dockerfile: Dockerfile
        ports:
            - '80:80'
        restart: always