FROM node:18.3.0-alpine

ADD . /code/rest
ENV PATH /code/node_modules/.bin:$PATH

COPY package.json /code
COPY package-lock.json /code

RUN cd /code && npm i

WORKDIR /code/rest

CMD ["npm", "run", "dev"]

EXPOSE 8080 9229